In [ ]:
import numpy as np
import pandas as pd

In [ ]:
import pandas as pd
df=pd.read_csv("/content/Dataset for Data Analytics - Sheet1.csv")

In [ ]:
df.head(5)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,1970-01-01 00:00:00.000000005,1970-01-01 00:00:00.000000570,928 Main St,Debit Card,Shipped,TRK37947903,1970-01-01 00:00:00.000000007,SAVE10,Instagram,1970-01-01 00:00:00.000002853
1,ORD200001,2024-08-23,C75739,Phone,1970-01-01 00:00:00.000000002,1970-01-01 00:00:00.000000151,823 Main St,Online,Shipped,TRK91186779,1970-01-01 00:00:00.000000003,SAVE10,Referral,1970-01-01 00:00:00.000000302
2,ORD200002,2024-02-27,C81728,Tablet,1970-01-01 00:00:00.000000005,1970-01-01 00:00:00.000000550,512 Main St,Credit Card,Cancelled,TRK42903982,1970-01-01 00:00:00.000000008,FREESHIP,Email,1970-01-01 00:00:00.000002753
3,ORD200003,2023-10-15,C33540,Chair,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000273,275 Main St,Debit Card,Returned,TRK62788070,1970-01-01 00:00:00.000000005,SAVE10,Facebook,1970-01-01 00:00:00.000000273
4,ORD200004,2025-05-08,C81840,Printer,1970-01-01 00:00:00.000000004,1970-01-01 00:00:00.000000626,668 Main St,Online,Delivered,TRK29241424,1970-01-01 00:00:00.000000008,SAVE10,Email,1970-01-01 00:00:00.000002504

In [ ]:
df.shape

(1200, 14)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   object
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: float64(2), int64(2), object(10)
memory usage: 131.4+ KB

In [ ]:
df.describe()

          Quantity    UnitPrice  ItemsInCart   TotalPrice
count  1200.000000  1200.000000  1200.000000  1200.000000
mean      2.945833   356.412750     5.485000  1053.968300
std       1.407557   197.177146     2.281983   819.856558
min       1.000000    11.390000     1.000000    11.390000
25%       2.000000   186.062500     4.000000   410.520000
50%       3.000000   364.210000     5.000000   823.615000
75%       4.000000   521.570000     7.000000  1578.475000
max       5.000000   699.930000    10.000000  3456.400000

In [ ]:
print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [ ]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)

/tmp/ipykernel_2581/1384138331.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [ ]:
print("Duplicate rows:", df.duplicated().sum())

df.drop_duplicates(inplace=True)

print("After removing duplicates:", df.shape)

Duplicate rows: 0
After removing duplicates: (1200, 14)

In [ ]:
for col in df.columns:
    try:
        df[col] = pd.to_datetime(df[col])
    except:
        pass

/tmp/ipykernel_2581/942444854.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
/tmp/ipykernel_2581/942444854.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
/tmp/ipykernel_2581/942444854.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
/tmp/ipykernel_2581/942444854.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
/tmp/ipykernel_2581/942444854.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
/tmp/ipykernel_2581/942444854.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
/tmp/ipykernel_2581/942444854.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
/tmp/ipykernel_2581/942444854.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])
/tmp/ipykernel_2581/942444854.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col])

In [ ]:
print("\nFinal Shape:", df.shape)

Final Shape: (1200, 14)

In [ ]:
print("\nRemaining Missing Values:")
print(df.isnull().sum())

Remaining Missing Values:
OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

In [ ]:
print("\nData Types:")
print(df.dtypes)

Data Types:
OrderID                    object
Date               datetime64[ns]
CustomerID                 object
Product                    object
Quantity           datetime64[ns]
UnitPrice          datetime64[ns]
ShippingAddress            object
PaymentMethod              object
OrderStatus                object
TrackingNumber             object
ItemsInCart        datetime64[ns]
CouponCode                 object
ReferralSource             object
TotalPrice         datetime64[ns]
dtype: object

In [ ]:
df.to_csv("cleaned_dataset.csv", index=False)

print("\nDataset cleaned successfully.")
print("File saved as: cleaned_dataset.csv")

Dataset cleaned successfully.
File saved as: cleaned_dataset.csv